import java.sql.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class MoneyTransfer extends javax.swing.JFrame {

    /**
     * Creates new form MoneyTransfer
     */
    
    int id; 
    int balance;
    String accno = new String();
    
    public MoneyTransfer() {
        initComponents();
        Account a = new Account();
        accno = a.findaccno(id);
        balance = a.getbalance(accno);
        a.setDetails();
    }
    
    public MoneyTransfer(int ID) {
        initComponents();
        id = ID;
        Account a = new Account();
        accno = a.findaccno(id);
        balance = a.getbalance(accno);
        a.setDetails();
    }
    
    class Account{
        String findaccno(int id){
          try {
            String url ="jdbc:mysql://localhost:3306/project";
            String user="root";
            String pass="14402084aA@";
            String query="Select accountno from user where userID ="+id;
            Connection con = DriverManager.getConnection(url, user, pass);
            Statement st = con.createStatement();
            ResultSet rs =st.executeQuery(query);
            rs.next();
            return rs.getString(1);
          } 
          catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex+"findaccno");
          }
          return  "x";
        }
        
        boolean checkaccount(String accno){
              try {
                    String url ="jdbc:mysql://localhost:3306/project";
                    String user="root";
                    String pass="14402084aA@";
                    String query="Select  accountno from Account";
                    Connection con = DriverManager.getConnection(url, user, pass);
                    Statement st = con.createStatement();
                    ResultSet rs =st.executeQuery(query);
                    while(rs.next())
                    {
                      if(rs.getString(1).equals(accno)){
                        return true;
                      }
                    }
                return false;
              } 
              catch (Exception e) {
                //TODO: handle exception
              }
              return false;
            }
        
        int getbalance(String accno){
            try{
                String url ="jdbc:mysql://localhost:3306/project";
                String user="root";
                String pass="14402084aA@";
                String query="Select balance from Account where accountno ="+accno;
                Connection con = DriverManager.getConnection(url, user, pass);
                Statement st = con.createStatement();
                ResultSet rs =st.executeQuery(query);
                rs.next();
                return rs.getInt("balance");
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex+"getbalance");
            }
            return 0;
        }
        void setDetails(){
            AccountNumber.setText(accno);
            AvailableBalance.setText(""+balance);
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        AccountNumber = new javax.swing.JTextField();
        AvailableBalance = new javax.swing.JTextField();
        BeneficiaryName = new javax.swing.JTextField();
        BeneficiaryAccountNumber = new javax.swing.JTextField();
        AmountToTransfer = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ACCOUNT NUMBER");

        jLabel3.setText("AVAILABLE BALANCE");

        jLabel5.setText("AMOUNT TO TRANSFER");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("ACCOUNT SUMMARY");

        jLabel7.setText("BENEFICIARY NAME");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setText("TRANSFER MONEY");

        jLabel9.setText("BENEFICIARY ACCOUNT NUMBER");

        jButton1.setText("TRANSFER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        AccountNumber.setEditable(false);

        AvailableBalance.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel10.setText("THE BANK OF LNMIIT ");
        jLabel10.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(AccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(97, 97, 97)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(BeneficiaryName, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BeneficiaryAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AmountToTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(67, 67, 67)
                                    .addComponent(AvailableBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel10)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AvailableBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BeneficiaryName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BeneficiaryAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(AmountToTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    class transaction{
          int transactionamt;
          String date_transaction;
          String withdrawaccno;
          String depoaccno;
          String status;
          
          void setTransaction(int tranAmt, String date, String waccno, String daccno, String Stat){
                transactionamt = tranAmt;
                date_transaction = date;
                withdrawaccno = waccno;
                depoaccno = daccno;
                status = Stat;
          }
          
          void insertTran(){
            try{
               if(transactionamt<balance){
                    Account a = new Account();
                    boolean exist = a.checkaccount(depoaccno);
                    if(exist){
                        String url ="jdbc:mysql://localhost:3306/project";
                        String user="root";
                        String pass="14402084aA@";
                        String query="Insert into Transaction (transactionAmount,dateoftransaction,WithdrawAccNo,DepositAccNo, statusOfTrans) values (?,?,?,?,?)";
                        Connection con = DriverManager.getConnection(url, user, pass);
                        PreparedStatement pst;
                        pst=con.prepareStatement(query);
                        pst.setInt(1,transactionamt);
                        pst.setString(2,date_transaction);
                        pst.setString(3,withdrawaccno);
                        pst.setString(4,depoaccno);
                        pst.setString(5,status);
                        pst.executeUpdate();
                        depositmoney(depoaccno,transactionamt);
                        withdrawmoney(withdrawaccno,transactionamt);
                        Account b = new Account();
                        balance = b.getbalance(accno);
                        b.setDetails();
                        JOptionPane.showMessageDialog(null, "Money Successfully Transferred");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Account Number Do not Exist");
                    }
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "Insufficient Balance");
                }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        
        void depositmoney(String accno,int money){
            try{
                String url ="jdbc:mysql://localhost:3306/project";
                String user="root";
                String pass="14402084aA@";
                Connection con = DriverManager.getConnection(url, user, pass);
                Account a = new Account();
                int bal= a.getbalance(accno);
                bal =bal+money;
                String query="UPDATE Account SET balance= (?) WHERE accountno="+accno;
                PreparedStatement pst;
                pst=con.prepareStatement(query);
                pst.setInt(1,bal);
                pst.executeUpdate();
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        void withdrawmoney(String accno,int money){
            try{
                String url ="jdbc:mysql://localhost:3306/project";
                String user="root";
                String pass="14402084aA@";
                Connection con = DriverManager.getConnection(url, user, pass);
                Account a = new Account();
                int bal= a.getbalance(accno);
                if(bal>=money){
                    bal =bal-money;
                    String query="UPDATE Account SET balance= (?) WHERE accountno="+accno;
                    PreparedStatement pst;
                    pst=con.prepareStatement(query);
                    pst.setInt(1,bal);
                    pst.executeUpdate();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Insufficient Balance");
                }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }

        }
          
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //String name = BeneficiaryName.getText();
       String sendAccNo = BeneficiaryAccountNumber.getText();
       int amount = Integer.parseInt(AmountToTransfer.getText());
       transaction tran = new transaction();
       String date = ""+java.time.LocalDate.now();
       tran.setTransaction(amount,date,accno,sendAccNo,"Success");
       tran.insertTran();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MainPage mFrame = new MainPage(id);
        mFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoneyTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoneyTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoneyTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoneyTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoneyTransfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountNumber;
    private javax.swing.JTextField AmountToTransfer;
    private javax.swing.JTextField AvailableBalance;
    private javax.swing.JTextField BeneficiaryAccountNumber;
    private javax.swing.JTextField BeneficiaryName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
